---
- name: make a build dir
  file: state=directory name=/root/deluge-dockerized

- name: put Dockerfile
  template: src=Dockerfile dest=/root/deluge-dockerized/Dockerfile

- name: put deluge.rb
  template: src=deluge.rb dest=/root/deluge-dockerized/deluge.rb

- name: put deluge-web.sh
  template: src=deluge-web.sh dest=/root/deluge-dockerized/deluge-web.sh mode=0755

- name: build a Docker image for deluge
  command: docker build -t gitinsky/deluge:0.2.0 --rm /root/deluge-dockerized
